const API = "https://dashboard-cenario-dos-lagos.vercel.app/api/metrics";

const semanas = [
  { semana: 1, inicio: "2026-03-01", fim: "2026-03-07", canais: {
    "Google Ads": { investimento: 3200, leads: 45, vendas: 0, valorVendas: 0, leadsQualificados: 14, comparecimentos: 5, slaRespostaMin: 3 },
    "Meta Ads": { investimento: 4800, leads: 82, vendas: 1, valorVendas: 420000, leadsQualificados: 28, comparecimentos: 10, slaRespostaMin: 4 },
    "Outdoor": { investimento: 2500, leads: 8, vendas: 0, valorVendas: 0, leadsQualificados: 3, comparecimentos: 1, slaRespostaMin: 8 },
    "Rádio": { investimento: 1800, leads: 5, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 12 },
    "Site": { investimento: 500, leads: 12, vendas: 0, valorVendas: 0, leadsQualificados: 5, comparecimentos: 2, slaRespostaMin: 2 },
    "Jornal": { investimento: 1200, leads: 3, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 15 },
    "Outros": { investimento: 800, leads: 4, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 10 },
    "Indicação": { investimento: 0, leads: 6, vendas: 1, valorVendas: 450000, leadsQualificados: 4, comparecimentos: 3, slaRespostaMin: 5 },
    "Contato Corretor": { investimento: 0, leads: 3, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 3 },
  }},
  { semana: 2, inicio: "2026-03-08", fim: "2026-03-14", canais: {
    "Google Ads": { investimento: 3500, leads: 52, vendas: 1, valorVendas: 460000, leadsQualificados: 18, comparecimentos: 7, slaRespostaMin: 3 },
    "Meta Ads": { investimento: 5200, leads: 95, vendas: 2, valorVendas: 880000, leadsQualificados: 32, comparecimentos: 12, slaRespostaMin: 4 },
    "Outdoor": { investimento: 2500, leads: 10, vendas: 0, valorVendas: 0, leadsQualificados: 4, comparecimentos: 2, slaRespostaMin: 7 },
    "Rádio": { investimento: 1800, leads: 7, vendas: 0, valorVendas: 0, leadsQualificados: 3, comparecimentos: 1, slaRespostaMin: 10 },
    "Site": { investimento: 500, leads: 15, vendas: 0, valorVendas: 0, leadsQualificados: 6, comparecimentos: 3, slaRespostaMin: 2 },
    "Jornal": { investimento: 1200, leads: 4, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 14 },
    "Outros": { investimento: 600, leads: 3, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 9 },
    "Indicação": { investimento: 0, leads: 8, vendas: 1, valorVendas: 450000, leadsQualificados: 5, comparecimentos: 4, slaRespostaMin: 4 },
    "Contato Corretor": { investimento: 0, leads: 5, vendas: 1, valorVendas: 430000, leadsQualificados: 3, comparecimentos: 2, slaRespostaMin: 3 },
  }},
  { semana: 3, inicio: "2026-03-15", fim: "2026-03-21", canais: {
    "Google Ads": { investimento: 4000, leads: 58, vendas: 1, valorVendas: 470000, leadsQualificados: 20, comparecimentos: 8, slaRespostaMin: 2 },
    "Meta Ads": { investimento: 5500, leads: 105, vendas: 2, valorVendas: 920000, leadsQualificados: 35, comparecimentos: 14, slaRespostaMin: 3 },
    "Outdoor": { investimento: 2500, leads: 12, vendas: 1, valorVendas: 440000, leadsQualificados: 5, comparecimentos: 3, slaRespostaMin: 6 },
    "Rádio": { investimento: 1800, leads: 6, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 11 },
    "Site": { investimento: 500, leads: 18, vendas: 1, valorVendas: 455000, leadsQualificados: 8, comparecimentos: 4, slaRespostaMin: 2 },
    "Jornal": { investimento: 1200, leads: 5, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 13 },
    "Outros": { investimento: 500, leads: 2, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 8 },
    "Indicação": { investimento: 0, leads: 10, vendas: 2, valorVendas: 910000, leadsQualificados: 7, comparecimentos: 5, slaRespostaMin: 4 },
    "Contato Corretor": { investimento: 0, leads: 4, vendas: 1, valorVendas: 450000, leadsQualificados: 3, comparecimentos: 2, slaRespostaMin: 3 },
  }},
  { semana: 4, inicio: "2026-03-22", fim: "2026-03-28", canais: {
    "Google Ads": { investimento: 3800, leads: 48, vendas: 1, valorVendas: 450000, leadsQualificados: 16, comparecimentos: 6, slaRespostaMin: 3 },
    "Meta Ads": { investimento: 5000, leads: 88, vendas: 1, valorVendas: 460000, leadsQualificados: 30, comparecimentos: 11, slaRespostaMin: 5 },
    "Outdoor": { investimento: 2500, leads: 9, vendas: 0, valorVendas: 0, leadsQualificados: 3, comparecimentos: 1, slaRespostaMin: 7 },
    "Rádio": { investimento: 1800, leads: 4, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 14 },
    "Site": { investimento: 500, leads: 14, vendas: 0, valorVendas: 0, leadsQualificados: 6, comparecimentos: 3, slaRespostaMin: 2 },
    "Jornal": { investimento: 1200, leads: 3, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 16 },
    "Outros": { investimento: 700, leads: 5, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 9 },
    "Indicação": { investimento: 0, leads: 7, vendas: 1, valorVendas: 450000, leadsQualificados: 5, comparecimentos: 3, slaRespostaMin: 5 },
    "Contato Corretor": { investimento: 0, leads: 4, vendas: 1, valorVendas: 440000, leadsQualificados: 3, comparecimentos: 2, slaRespostaMin: 4 },
  }},
  { semana: 5, inicio: "2026-03-29", fim: "2026-04-04", canais: {
    "Google Ads": { investimento: 4200, leads: 62, vendas: 2, valorVendas: 920000, leadsQualificados: 22, comparecimentos: 9, slaRespostaMin: 2 },
    "Meta Ads": { investimento: 6000, leads: 115, vendas: 3, valorVendas: 1350000, leadsQualificados: 40, comparecimentos: 16, slaRespostaMin: 3 },
    "Outdoor": { investimento: 3000, leads: 14, vendas: 1, valorVendas: 460000, leadsQualificados: 6, comparecimentos: 3, slaRespostaMin: 6 },
    "Rádio": { investimento: 2000, leads: 8, vendas: 0, valorVendas: 0, leadsQualificados: 3, comparecimentos: 1, slaRespostaMin: 9 },
    "Site": { investimento: 500, leads: 20, vendas: 1, valorVendas: 470000, leadsQualificados: 9, comparecimentos: 5, slaRespostaMin: 2 },
    "Jornal": { investimento: 1500, leads: 6, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 12 },
    "Outros": { investimento: 800, leads: 5, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 8 },
    "Indicação": { investimento: 0, leads: 12, vendas: 2, valorVendas: 900000, leadsQualificados: 8, comparecimentos: 6, slaRespostaMin: 4 },
    "Contato Corretor": { investimento: 0, leads: 6, vendas: 1, valorVendas: 460000, leadsQualificados: 4, comparecimentos: 3, slaRespostaMin: 3 },
  }},
  { semana: 6, inicio: "2026-04-05", fim: "2026-04-11", canais: {
    "Google Ads": { investimento: 4500, leads: 68, vendas: 2, valorVendas: 940000, leadsQualificados: 24, comparecimentos: 10, slaRespostaMin: 2 },
    "Meta Ads": { investimento: 6500, leads: 120, vendas: 3, valorVendas: 1380000, leadsQualificados: 42, comparecimentos: 17, slaRespostaMin: 3 },
    "Outdoor": { investimento: 3000, leads: 11, vendas: 0, valorVendas: 0, leadsQualificados: 4, comparecimentos: 2, slaRespostaMin: 7 },
    "Rádio": { investimento: 2000, leads: 6, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 10 },
    "Site": { investimento: 500, leads: 22, vendas: 1, valorVendas: 450000, leadsQualificados: 10, comparecimentos: 5, slaRespostaMin: 2 },
    "Jornal": { investimento: 1500, leads: 4, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 18 },
    "Outros": { investimento: 600, leads: 3, vendas: 0, valorVendas: 0, leadsQualificados: 1, comparecimentos: 0, slaRespostaMin: 11 },
    "Indicação": { investimento: 0, leads: 9, vendas: 2, valorVendas: 880000, leadsQualificados: 6, comparecimentos: 5, slaRespostaMin: 4 },
    "Contato Corretor": { investimento: 0, leads: 5, vendas: 1, valorVendas: 450000, leadsQualificados: 3, comparecimentos: 2, slaRespostaMin: 3 },
  }},
  { semana: 7, inicio: "2026-04-12", fim: "2026-04-18", canais: {
    "Google Ads": { investimento: 4800, leads: 72, vendas: 2, valorVendas: 900000, leadsQualificados: 25, comparecimentos: 11, slaRespostaMin: 2 },
    "Meta Ads": { investimento: 7000, leads: 130, vendas: 4, valorVendas: 1800000, leadsQualificados: 45, comparecimentos: 18, slaRespostaMin: 3 },
    "Outdoor": { investimento: 3000, leads: 15, vendas: 1, valorVendas: 470000, leadsQualificados: 6, comparecimentos: 4, slaRespostaMin: 5 },
    "Rádio": { investimento: 2200, leads: 9, vendas: 1, valorVendas: 440000, leadsQualificados: 4, comparecimentos: 2, slaRespostaMin: 8 },
    "Site": { investimento: 500, leads: 25, vendas: 1, valorVendas: 460000, leadsQualificados: 11, comparecimentos: 6, slaRespostaMin: 2 },
    "Jornal": { investimento: 1500, leads: 5, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 14 },
    "Outros": { investimento: 900, leads: 6, vendas: 0, valorVendas: 0, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 7 },
    "Indicação": { investimento: 0, leads: 14, vendas: 3, valorVendas: 1350000, leadsQualificados: 10, comparecimentos: 7, slaRespostaMin: 3 },
    "Contato Corretor": { investimento: 0, leads: 7, vendas: 2, valorVendas: 890000, leadsQualificados: 5, comparecimentos: 4, slaRespostaMin: 3 },
  }},
  { semana: 8, inicio: "2026-04-19", fim: "2026-04-25", canais: {
    "Google Ads": { investimento: 5000, leads: 78, vendas: 3, valorVendas: 1380000, leadsQualificados: 28, comparecimentos: 12, slaRespostaMin: 2 },
    "Meta Ads": { investimento: 7500, leads: 140, vendas: 4, valorVendas: 1850000, leadsQualificados: 48, comparecimentos: 20, slaRespostaMin: 3 },
    "Outdoor": { investimento: 3500, leads: 18, vendas: 1, valorVendas: 480000, leadsQualificados: 7, comparecimentos: 4, slaRespostaMin: 5 },
    "Rádio": { investimento: 2200, leads: 10, vendas: 1, valorVendas: 450000, leadsQualificados: 4, comparecimentos: 2, slaRespostaMin: 8 },
    "Site": { investimento: 500, leads: 28, vendas: 2, valorVendas: 920000, leadsQualificados: 12, comparecimentos: 7, slaRespostaMin: 1 },
    "Jornal": { investimento: 1500, leads: 6, vendas: 1, valorVendas: 430000, leadsQualificados: 2, comparecimentos: 1, slaRespostaMin: 13 },
    "Outros": { investimento: 1000, leads: 7, vendas: 0, valorVendas: 0, leadsQualificados: 3, comparecimentos: 1, slaRespostaMin: 7 },
    "Indicação": { investimento: 0, leads: 16, vendas: 3, valorVendas: 1400000, leadsQualificados: 12, comparecimentos: 9, slaRespostaMin: 3 },
    "Contato Corretor": { investimento: 0, leads: 8, vendas: 2, valorVendas: 920000, leadsQualificados: 6, comparecimentos: 5, slaRespostaMin: 2 },
  }},
];

const res = await fetch(API, {
  method: "PUT",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    config: { vgv: { totalUnidades: 178, ticketMedio: 450000, vgvTotal: 80100000 } },
    semanas,
  }),
});
const result = await res.json();
console.log("Resultado:", JSON.stringify(result));
